config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, allow_blank: true
  validates_uniqueness_of :movie_id, :scope => [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies
  has_one_attached :photo
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    # @movie = Movie.find(params[:bookmark][:movie.id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container col-6">
    <h3 class="display-4" class="p-2 bg-light border">Add New Bookmark</h3>
    <hr class="my-4">
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie, as: :select %>
      <%= f.input :comment %>
      <br>
      <%= f.submit  %>
    <% end %>
    <br>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="https://cdn-icons-png.flaticon.com/512/390/390067.png" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
            <button class="btn btn-outline-dark"><a class="nav-link" href="#">Home</a></button>
            </li>
            <button type="button" class="btn btn-secondary">
            <%= link_to "Add a new list", new_list_path, class:"text-white text-decoration-none" %>
            </button>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle mt-2" src="https://cdn-icons-png.flaticon.com/512/705/705062.png" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    <div class="footer-copyright">
      This footer is made with <img class="footer-icon" src="https://cdn-icons-png.flaticon.com/512/2917/2917656.png" alt=""> at Le Wagon
    </div>
  </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <br>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.istockphoto.com/photos/film-reels-on-black-background-movie-video-and-cinema-prodaction-and-picture-id1336937059?k=20&m=1336937059&s=612x612&w=0&h=x6LbQl2wKDTqQzZCwL8ihiZFEFBfgPh-KcoCLnefRx0=);">
  <div class="container">
    <h1>Discover the world of <strong>movies</strong> !</h1>
    <br>
    <br>
    <a class="btn btn-outline-light" href="#">Find out more</a>
  </div>
</div>
<div class="cards">
  <% @lists.each do |list| %>
    <% if list.photo.attached? %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')"><%= link_to list.name, list_path(list) %></div>
    <% else %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/photos/old-blank-ticket-picture-id484126086?k=20&m=484126086&s=170667a&w=0&h=q-mmvYp5Qrqo07SySYU5S-x2RGKMqqggu1dcucn0CmE=)">
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container col-6">
    <h3 class="display-4" class="p-2 bg-light border">Add New List</h3>
    <hr class="my-4">
    <%= render 'form' %>
    <br>
    <div class="btn btn-secondary">
      <%= link_to "Back to Lists", lists_path, class: "text-white text-decoration-none"%>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="jumbotron jumbotron-fluid mt-5">
  <div class="container col-6">
    <span class="p-2 bg-light">
    <h3 class="display-4" class="p-2 bg-light border"><%= @list.name %></h3>
    <% if @list.photo.attached? %>
      <%= cl_image_tag @list.photo.key, height: 600, width: 700, crop: :fill %>
    <% else %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg" %>
    <% end %>
    <hr class="my-4">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card">
      <h5 class="movie-title">Movie Title: <%= bookmark.movie.title %></h5>
      <p class="p-2 bg-light border d-flex justify-content-between">Review: <%= bookmark.comment %>
      <%= link_to bookmark_path(bookmark),
              method: :delete,
              data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-trash-alt"></i>
              <% end %></p></div>
    <% end %>
    <br>
    </span>
    <div class="btn btn-secondary">
      <%= link_to "Back to Lists", lists_path, class: "text-white text-decoration-none"%>
    </div>
    <div class="btn btn-secondary">
      <%= link_to "Create a bookmark", new_list_bookmark_path(@list), class: "text-white text-decoration-none"%>
    </div>
  </div>
</div>